[package]
name = "chessier"
version = "0.1.0"
authors = ["Andrew Chien <aechien@gmail.com>"]
edition = "2018"

[[bin]]
name="perft"
path="src/bin/perft.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum="0.4"
num="0.2"